services:
  app:
    build: .
    image: ghcr.io/nikita-skakun/flux360:latest
    container_name: flux360
    volumes:
      - ./data:/app/data:rw
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - edge

networks:
  edge:
    external: true